const SUPABASE_URL = 'https://uyqkdwazxrqaxmjwglmc.supabase.co';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5cWtkd2F6eHJxYXhtandnbG1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM3MzI4NTIsImV4cCI6MjA4OTMwODg1Mn0.n-oLsHFOJI5shvWsGn1WvLOhtYMeCe148XtwHP80Zxc';
